### ISSUE TITLE
Carousel widget for What We've Done

### ISSUE THREAD

**Issue by kbaley** [westerndevs/western-devs-website#106]
What We've Done widget should scroll through a list of things we've done.

Possible implementation: Create a folder containing banner images of a uniform size. The plugin can iterate through these images. For books, we can include three per image. Prairie Dev Con should have its own image.

All images should link to the What We've Done page

**Comment by dpaquette** [comment]
Depending on the renderer we use this could just be a page. Might not need to be a plugin

**Comment by kbaley** [comment]
I meant a widget, not a plugin

**Comment by dpaquette** [comment]
What do you mean by scroll through?  Are you looking for a carousel type thing?

**Comment by kbaley** [comment]
Yes, a carousel.

**Comment by davidwesst** [comment]
We'll need to update the data to make sure that everyone has "done something". As it stands, I have "done nothing" but would have something if we included conferences.

Lastly, where do we want the widget to appear. A couple of ideas:
- Sidebar on posts
- Sidebar on author page

**Comment by kbaley** [comment]
@davidwesst This is for the home page. The What We've Done section is currently hard-coded. I'd rather it was dynamic like the Featured widget below it. So when the page loads, it chooses from a list of "what we've done" items and displays them.

Having them rotate in a carousel-fashion would be a bonus.

**Comment by kbaley** [comment]
Done
