### ISSUE TITLE
iTunes.xml

### ISSUE THREAD

**Issue by kbaley** [westerndevs/western-devs-website#118]

**Comment by kbaley** [comment]
The generator works fine for `/feed.xml` and `/itunes.xml`. At '/feed`, it wraps the XML within an HTML template:

![image](https://cloud.githubusercontent.com/assets/130546/11761869/6b0532b6-a0a1-11e5-94de-628f810b4dc6.png)


Assuming that's part of the generator and not this, :shipit:

**Comment by dbelcham** [comment]
addressed in PR with commit 7d2d103
