### ISSUE TITLE
Indicate podcasts in the posts listing

### ISSUE THREAD

**Issue by kbaley** [westerndevs/western-devs-website#124]
Not sure how to do this yet. Some options:

- Prefix the title with "Podcast:"
- Include the podcast icon

**Comment by dbelcham** [comment]
Add a tag and then display an icon/graphic based on it's existence?

**Comment by kbaley** [comment]
Don't need the tag. It's already in the category. Was just wondering how to indicate it visually.

**Comment by MisterJames** [comment]
@kbaley can this one be closed with #142?

**Comment by kbaley** [comment]
Is it worth indicating postcasts in the full post listing? http://www.westerndevs.com/posts/
