### ISSUE TITLE
Add Disqus comments

### ISSUE THREAD

**Issue by kbaley** [westerndevs/western-devs-website#15]

**Comment by dpaquette** [comment]
I would recommend using Disqus:
https://help.disqus.com/customer/portal/articles/472138-jekyll-installation-instructions

**Comment by amirci** [comment]
Where do you want them? everywhere? Perhaps as part of the footer?

**Comment by kbaley** [comment]
For now, on posts only. I think in the instructions, they give you the option of turning them on on a post-by-post basis.

**Comment by kbaley** [comment]
We'll need a separate Disqus account specifically for WesternDevs.
