### ISSUE TITLE
Migrate Disqus comments

### ISSUE THREAD

**Issue by kbaley** [westerndevs/western-devs-website#152]
Not sure why they haven't been migrated over. The URLs are all the same. Maybe try the Disqus migration tools.

**Comment by dpaquette** [comment]
This is very strange. Comments on my blog all came through automatically. I didn't have to do anything special.

**Comment by kbaley** [comment]
Yeah and if we switch back to the old design, they show up there as well. Plus it's showing "Also on Western Devs" which suggests the script is working to some extent.

**Comment by kbaley** [comment]
There is a hack now to address this: https://github.com/westerndevs/western-devs-website/commit/7d19a3d48b607010d9575e7b924a05b1456f4b03

The issue is with the Hexo permalink. It assumes there will always be at least one category. Because many of our posts don't have one, the permalink starts with two slashes. We'll need to fix this in our forked hexo repo or for hexo-util and fix it in the Permalink.js file there.
