### ISSUE TITLE
Add social links to posts

### ISSUE THREAD

**Issue by kbaley** [westerndevs/western-devs-website#16]
E.g. tweet this, share on facebook, etc.

**Comment by dpaquette** [comment]
I see the Twitter / Facebook / Google+ buttons are there now but the links are broken. They are trying to share the relative url (eg. /wherewellbe/ ) instead of the absolute url (http://www.westerndevs.com/wherewellbe/)

**Comment by kbaley** [comment]
Fixed in PR #21 

By default, it will use westerndevs.com as the site.url. To run locally, use:

`jekyll serve --config _config.yml,_config-dev.yml`
