### ISSUE TITLE
Explain GitHub to Rob

### ISSUE THREAD

**Issue by kbaley** [westerndevs/western-devs-website#163]

**Comment by rob-windsor** [comment]
So, it's a website?

**Comment by dbelcham** [comment]
Let me put this in Sharepoint terms for you.....

You know how you can checkout and checkin documents in a Sharepoint Document Library? Yah, it's like that...except it works...and it's collaborative...and you don't have to worry about that asshole in HR who locks a file and leaves for their ~conference~ holiday in Punta Cana

**Comment by kbaley** [comment]
@rob-windsor Did that help? Can I close this issue?

**Comment by rob-windsor** [comment]
@kbaley Absolutely, I am now a Git master!
