### ISSUE TITLE
Include recording date in metadata for podcasts

### ISSUE THREAD

**Issue by kbaley** [westerndevs/western-devs-website#171]

**Comment by davidwesst** [comment]
Is this data already on the site and just needs to be displayed, or do we need to add the data and display it on the page?

**Comment by kbaley** [comment]
Metadata for sure. Originally I thought we'd include it on the page as well because we have a pretty big lead time between recording and publishing. Do you think it adds value?

**Comment by davidwesst** [comment]
Personally, I don't think it adds value.

If we have a large lead time between recording and publishing, people might think that our content is out of date by the time they consume it. If the recording date matters, we should put it in the introduction with some context about why it's delayed.

Again, this is all just my opinion so take it for what it is.

**Comment by kbaley** [comment]
Just the metadata is fine. We don't need a reason for the delay. Most people will assume it's because we're lazy. Which is accurate so there's no need to advertise it.

**Comment by kbaley** [comment]
Fixed
