### ISSUE TITLE
Site is hard to read

### ISSUE THREAD

**Issue by dpaquette** [westerndevs/western-devs-website#211]
Consider increasing the line-height to 21px to improve readability of blog posts.

**Comment by stimms** [comment]
21px is not a prime number, request line height of 23 pixels

**Comment by dbelcham** [comment]
21 is part of the Fibonacci sequence and, thus, part of the Golden Ratio. Take _that_ Prime Numbers

**Comment by kbaley** [comment]
Fixed by #212
