### ISSUE TITLE
Add ability to delete ResourceGroup that is created with deploy.ps1

### ISSUE THREAD

**Issue by kbaley** [westerndevs/western-devs-website#80]
deploy.ps1 will create a new resource group in Azure. Would be nice to be able to delete it via a script rather than having to login to the portal.

**Comment by dylan-smith** [comment]
Not sure I see a tone of value in that.  if you already have a powershell window open that has been logged in to your azure account (say by running deploy.ps1), it's a simple matter of doing Remove-AzureResourceGroup -Name foo.  I suppose I could add a script for that, but the script would probably need to force you to login again, which seems like a pain.

I could see more value in adding something to the end of deploy.ps1 that paused for user input, and asked you if you wanted to delete it (y/n).  That way if you were just doing this to do a quick test, you could run deploy.ps1, then have it sit there at the "do you want to delete" prompt, while you did your testing, then come back to PS and hit Y and be done.  Is that what you were thinking?

**Comment by kbaley** [comment]
I didn't know that was an option. I'm not familiar with PS, let alone Azure's extensions. Adding something at the end of the deploy is a good idea because it removes the need to remember to do it yourself. Also would be good to include in the readme the command to remove the resource group.

**Comment by dylan-smith** [comment]
this was committed a while ago - forgot to close the issue
